Repository moevm/mse1h2024-assistant, pull requests merged in 2024-03, with the labels that each got.

#37 Объединение frontend и backend в 1 docker-compose
  backend/Dockerfile
  backend/backend/__main__.py
  backend/backend/config.ini
  backend/backend/settings.py
  backend/config.ini
  backend/requirements.txt
  docker-compose.yml
  frontend/Dockerfile
  frontend/docker-compose.yml
Labels: approved

#36 Разработать компонент стартовой страницы
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/logo.png
  frontend/src/App.vue
  frontend/src/assets/styles.scss
  frontend/src/components/Login.vue
  frontend/src/main.js
  frontend/vue.config.js
Labels: approved

#38 Разработать компонент чата на vue
  frontend/src/App.vue
  frontend/src/components/Chat.vue
  frontend/src/components/Login.vue
Labels: approved

#33 Исследование использования whisper для расшифровки аудио
  research/whisper/requirements.txt
  research/whisper/result/base.txt
  research/whisper/result/medium.txt
  research/whisper/result/small.txt
  research/whisper/result/tiny.txt
  research/whisper/samples/sample_1.ogg
  research/whisper/samples/sample_2.ogg
  research/whisper/samples/sample_3.ogg
  research/whisper/samples/sample_4.ogg
  research/whisper/samples/sample_5.ogg
  research/whisper/samples/sample_6.ogg
  research/whisper/samples/sample_7.ogg
  research/whisper/samples/sample_8.ogg
  research/whisper/samples/sample_9.ogg
  research/whisper/whisper.docx
  research/whisper/whisper.pdf
  research/whisper/whisper/test.py
Labels: documentation, approved

#41 Реализовать отправку голосовых сообщений с веб-версии фронтенда на бэкенд
  frontend/src/components/Chat.vue
Labels: approved

#35 Клиент на основе для взаимодействия с моделью с backend'а
  backend/backend/models/client.py
  backend/backend/routers/api.py
Labels: check needed

#42 Тг-бот для взаимодействия с бэкендом
  tg_bot/bot.py
  tg_bot/config.ini
  tg_bot/modules/logger.py
Labels: check needed, work in progress

#46 update config and docker
  backend/Dockerfile
  backend/README.md
  backend/backend/__main__.py
  backend/backend/settings.py
  backend/img.png
  backend/requirements.txt
Labels: approved

#48 Добавлена ollama в docker compose
  docker-compose.yml
Labels: approved, iteration 2

#50 Добавлен скрипт запуска с загрузкой модели
  backend/backend/models/test.py
  docker-compose.yml
  run.sh
Labels: approved, iteration 2

#52 обновление клиента
  backend/Dockerfile
  backend/backend/__main__.py
  backend/backend/config.ini
  backend/backend/models/client.py
  backend/backend/models/request.py
  backend/backend/routers/api.py
  backend/backend/settings.py
  docker-compose.yml
  frontend/src/components/Chat.vue
  frontend/src/components/Login.vue
  frontend/src/requests.js
Labels: approved
