Repository moevm/mse1h2024-assistant, pull requests merged in 2024-05, with the labels that each got.

#92 Интеграция tg-bot с celery
  tg_bot/config.ini
  tg_bot/modules/handlers.py
Labels: check needed

#95 Оценка оптимальных ограничений длины запроса к модели
  docs/Выявление оптимальной длины запроса.pdf
Labels: check needed

#96 Фикс бага при отправке аудио сообщения
  frontend/src/components/Chat.vue
  frontend/src/requests.js
Labels: check needed, iteration 4

#101 Добавлены ограничения для запросов от пользователя
  backend/backend/celery/worker.py
  backend/backend/config.ini
  backend/backend/models/client.py
  backend/backend/routers/api.py
  backend/backend/settings.py
  docker-compose.yml
  frontend/src/components/Chat.vue
  package-lock.json
  run.sh
Labels: approved

#100 Docker/docker-compose для tg_bot
  docker-compose.yml
  tg_bot/Dockerfile
  tg_bot/bot.py
  tg_bot/config.ini
  tg_bot/requirements.txt
Labels: approved, iteration 4

#98 Интеграционные тесты между backend и tg-bot
  tg_bot/test_bot.py
Labels: approved, iteration 4

#97 Интеграционные тесты между backend и frontend
  frontend/DockerfileTest
  frontend/README.md
  frontend/package.json
  frontend/tests/integration/api.test.js
Labels: fix needed, iteration 4

#103 Интеграция тестов tg_bot c docker
  tg_bot/DockerfileTest
  tg_bot/requirements.txt
  tg_bot/test_bot.py
Labels: approved

#99 Интеграционные тесты между backend и whisper
  backend/Dockerfile
  backend/backend/celery/worker.py
  backend/backend/config.ini
  backend/backend/settings.py
  backend/backend/whisper/whisper.py
  backend/pytest.ini
  backend/requirements.txt
  backend/tests/test_routers.py
  backend/tests/whisper/test_audio.ogg
  backend/tests/whisper/test_whisper.py
Labels: approved

#105 Доработка бота
  tg_bot/modules/handlers.py
  tg_bot/test_bot.py
Labels: check needed, iteration 4

#107 Добавлена простейшая защита от спама
  tg_bot/__pycache__/test_bot.cpython-310-pytest-8.2.1.pyc
  tg_bot/modules/__pycache__/handlers.cpython-310.pyc
  tg_bot/modules/__pycache__/logger.cpython-310.pyc
Labels: approved, iteration 4

#104 Анализ модели и промпта для улучшения ответа модели
  backend/backend/config.ini
  backend/backend/models/client.py
  research/Практическое сравнение LLM.pdf
  research/Тестирование промпта для ограничения вопросов вне контекста.pdf
  run.sh
Labels: approved

#108 Выбор окончательного промпта для модели
  backend/backend/models/client.py
  research/Использование промпт-инжиниринга для улучшение результата вывода модели.pdf
Labels: approved, iteration 4

#111 Интеграция тестов backend whisper с Docker
  backend/DockerfileTest
Labels: approved

#114 Обновлены инструкции по запуску и тестированию
  backend/README.md
  tg_bot/README.MD
Labels: approved

#115 Исправление инструкций
  README.md
  frontend/README.md
  frontend/src/components/Chat.vue
  Инструкция проверки корректности работы сервиса.md
Labels: approved, iteration 4

#112 Минимальная защита от спама
  tg_bot/modules/handlers.py
Labels: approved, iteration 4

#117 Автоматизация докер тестов для бэкенда
  backend/DockerfileTest
  backend/README.md
  backend/tests/__init__.py
  backend/tests/test_audio.ogg
  backend/tests/test_routers.py
  backend/tests/test_whisper.py
Labels: approved, iteration 4
